"""add artwork dimensions

Revision ID: 27803da7616e
Revises: 9e40564d3748
Create Date: 2025-12-03 19:07:39.378634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27803da7616e'
down_revision: Union[str, Sequence[str], None] = '9e40564d3748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('artworks', sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('artworks', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_unique_constraint('uq_websites_artist_id', 'websites', ['artist_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_websites_artist_id', 'websites', type_='unique')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_column('artworks', 'length')
    op.drop_column('artworks', 'width')
    op.drop_column('artworks', 'height')
    # ### end Alembic commands ###
