"""initial schema

Revision ID: 816efebf88ab
Revises: 160b5e71391f
Create Date: 2025-11-18 20:41:53.713891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816efebf88ab'
down_revision: Union[str, Sequence[str], None] = '160b5e71391f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('like_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_index(op.f('ix_likes_target_id'), 'likes', ['target_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('views',
    sa.Column('view_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_index(op.f('ix_views_session_id'), 'views', ['session_id'], unique=False)
    op.create_index(op.f('ix_views_target_id'), 'views', ['target_id'], unique=False)
    op.create_table('watch_time',
    sa.Column('watch_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('seconds_watched', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('watch_id')
    )
    op.create_index(op.f('ix_watch_time_target_id'), 'watch_time', ['target_id'], unique=False)
    op.create_table('artworks',
    sa.Column('artwork_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=2048), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_for_sale', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artwork_id')
    )
    op.create_index(op.f('ix_artworks_artist_id'), 'artworks', ['artist_id'], unique=False)
    op.create_table('exhibitions',
    sa.Column('exhibition_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_music_url', sa.String(length=2048), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('published_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exhibition_id')
    )
    op.create_index(op.f('ix_exhibitions_artist_id'), 'exhibitions', ['artist_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_artist_id'), 'orders', ['artist_id'], unique=False)
    op.create_table('websites',
    sa.Column('website_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('published_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('website_id')
    )
    op.create_index(op.f('ix_websites_artist_id'), 'websites', ['artist_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_target_id'), 'order_items', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_target_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_websites_artist_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_orders_artist_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_exhibitions_artist_id'), table_name='exhibitions')
    op.drop_table('exhibitions')
    op.drop_index(op.f('ix_artworks_artist_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_watch_time_target_id'), table_name='watch_time')
    op.drop_table('watch_time')
    op.drop_index(op.f('ix_views_target_id'), table_name='views')
    op.drop_index(op.f('ix_views_session_id'), table_name='views')
    op.drop_table('views')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_likes_target_id'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
