"""add composite indexes for analytics and dashboards

Revision ID: 99ac4d2a22fb
Revises: 9abb6837542b
Create Date: 2025-11-27 14:52:30.730103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ac4d2a22fb'
down_revision: Union[str, Sequence[str], None] = '9abb6837542b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_artworks_artist_status', 'artworks', ['artist_id', 'status'], unique=False)
    op.create_index('ix_exhibitions_artist_deleted_status', 'exhibitions', ['artist_id', 'is_deleted', 'status'], unique=False)
    op.create_index('ix_likes_target_type_id_created', 'likes', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_order_items_source_type_id', 'order_items', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_order_items_target_type_id', 'order_items', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_orders_artist_status', 'orders', ['artist_id', 'status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_reviews_target_type_id_created', 'reviews', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_views_target_type_id_created', 'views', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_watch_time_target_type_id_created', 'watch_time', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_websites_artist_deleted_status', 'websites', ['artist_id', 'is_deleted', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_websites_artist_deleted_status', table_name='websites')
    op.drop_index('ix_watch_time_target_type_id_created', table_name='watch_time')
    op.drop_index('ix_views_target_type_id_created', table_name='views')
    op.drop_index('ix_reviews_target_type_id_created', table_name='reviews')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index('ix_orders_artist_status', table_name='orders')
    op.drop_index('ix_order_items_target_type_id', table_name='order_items')
    op.drop_index('ix_order_items_source_type_id', table_name='order_items')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index('ix_likes_target_type_id_created', table_name='likes')
    op.drop_index('ix_exhibitions_artist_deleted_status', table_name='exhibitions')
    op.drop_index('ix_artworks_artist_status', table_name='artworks')
    # ### end Alembic commands ###
