"""update schema for soft delete + notifications

Revision ID: 9abb6837542b
Revises: cc30b7f96524
Create Date: 2025-11-27 14:20:35.713014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9abb6837542b'
down_revision: Union[str, Sequence[str], None] = 'cc30b7f96524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('artworks', 'file_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('exhibitions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('exhibitions', 'background_music_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('exhibitions', 'published_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'profile_pic',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('websites', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('websites', 'published_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('websites', 'published_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               existing_nullable=True)
    op.drop_column('websites', 'is_deleted')
    op.alter_column('users', 'profile_pic',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               existing_nullable=True)
    op.alter_column('exhibitions', 'published_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               existing_nullable=True)
    op.alter_column('exhibitions', 'background_music_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               existing_nullable=True)
    op.drop_column('exhibitions', 'is_deleted')
    op.alter_column('artworks', 'file_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048),
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
