"""add thumbnail_url to exhibitions

Revision ID: 9e40564d3748
Revises: 99ac4d2a22fb
Create Date: 2025-11-28 11:22:27.007338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e40564d3748'
down_revision: Union[str, Sequence[str], None] = '99ac4d2a22fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitions', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitions', 'thumbnail_url')
    # ### end Alembic commands ###
