"""add artwork metadata fields

Revision ID: cc30b7f96524
Revises: 816efebf88ab
Create Date: 2025-11-25 19:59:17.897896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc30b7f96524'
down_revision: Union[str, Sequence[str], None] = '816efebf88ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('artworks', sa.Column('availability', sa.String(length=100), nullable=True))
    op.add_column('artworks', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('artworks', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('edition_current', sa.Integer(), nullable=True))
    op.add_column('artworks', sa.Column('edition_total', sa.Integer(), nullable=True))
    op.drop_column('artworks', 'is_for_sale')
    op.drop_column('artworks', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=True))
    op.add_column('artworks', sa.Column('is_for_sale', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('artworks', 'edition_total')
    op.drop_column('artworks', 'edition_current')
    op.drop_column('artworks', 'tags')
    op.drop_column('artworks', 'category')
    op.drop_column('artworks', 'availability')
    op.drop_column('artworks', 'year')
    # ### end Alembic commands ###
